# Generated by Django 4.2.1 on 2023-06-01 20:51

import aplicacion.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_invitacion', models.CharField(default=aplicacion.models.generar_codigo_invitacion, max_length=10, unique=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre', models.CharField(default='Mi Espacio', max_length=255)),
                ('descripcion', models.TextField(default='Espacio de trabajo personal')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuarios', models.ManyToManyField(related_name='espacios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
