# Generated by Django 4.2.1 on 2023-06-02 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaInformacionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ingreso', models.CharField(choices=[('Fijo', 'Fijo'), ('Esporádico', 'Esporádico')], max_length=20)),
                ('fuente_ingreso', models.CharField(choices=[('Trabajo', 'Trabajo'), ('Donaciones', 'Donaciones'), ('Pensión', 'Pensión'), ('Becas y/o Beneficios', 'Becas y/o Beneficios'), ('Bonos', 'Bonos'), ('Compensación', 'Compensación')], max_length=50)),
                ('monto_ingreso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hoja_informacion_financiera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.hojainformacionfinanciera')),
            ],
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_egreso', models.CharField(choices=[('Fijo', 'Fijo'), ('Esporádico', 'Esporádico')], max_length=20)),
                ('fuente_egreso', models.CharField(choices=[('Alimentación', 'Alimentación'), ('Transporte', 'Transporte'), ('Imprevistos', 'Imprevistos'), ('Salud', 'Salud'), ('Diversión', 'Diversión'), ('Educación', 'Educación'), ('Higiene', 'Higiene'), ('Vestuario', 'Vestuario'), ('Servicios Básicos', 'Servicios Básicos'), ('Servicios Tecnológicos', 'Servicios Tecnológicos'), ('Completos', 'Completos')], max_length=50)),
                ('monto_egreso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hoja_informacion_financiera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.hojainformacionfinanciera')),
            ],
        ),
    ]
